version: '3'

services:
  db:
    build: ./contents/mysql
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bowring
      MYSQL_USER: bowring
      MYSQL_PASSWORD: bowring
      TZ: 'Asia/Tokyo'
    command: --innodb-use-native-aio=0
    volumes:
      - ./cache/db/ :/var/lib/mysql
      - ./contents/mysql/conf.d :/etc/mysql/conf.d/
      - ./log/mysql :/var/log/mysql
    ports:
      - 33306:3306

  front:
    build: ./contents/front
    container_name: front
    ports:
      - "44200:4200"
    volumes:
      - "../bowring-front :/bowringfront"
    tty: true
    
  django:
    build: ./contents/server
    container_name: server
    restart: always
    ports:
      - "8000:8000"
    command: sh -c "sleep 5; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "../bowring_server :/code/bowringserver"
      - "./contents/server :/code" 
    depends_on:
      - db
    tty: true
    
  # phpMyAdmin
  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
